### ISSUE TITLE
Related model type is inferred as `mixed` by PHPStan / Larastan

### ISSUE THREAD

**Issue by sebj54** [staudenmeir/belongs-to-through#105] opened 2024-10-21 15:55 UTC
Hi there!

I am using your very useful package in a project where I am using PHPStan with level 9 (through Larastan). I recently updated dependencies in this project and I have several errors reported by PHPStan.

I know that there has been a few updates on generics both on Laravel and Larastan. I think one of these updates made the problem surface.

Here is a preview of the problem pointed by PHPStan (I changed the variables so you can understand my relations easily):

![image](https://github.com/user-attachments/assets/b9a71ae1-d063-4023-8947-665ac458f204)

```php
/**
 * @return BelongsToThrough<GrandParent, $this>
 */
public function grandParent(): BelongsToThrough
{
    return $this->belongsToThrough(GrandParent::class, Parent::class);
}
```

Let me know if you need a reproduction, I'll make a small project. Thanks for your help!

**Comment by staudenmeir** [comment] 2024-10-21 17:15
Hi @sebj54,

> Let me know if you need a reproduction, I'll make a small project.

That would be great, thanks.

**Comment by sebj54** [comment] 2024-10-22 09:32
Here it is: https://github.com/sebj54/debug-belongs-to-through-phpstan

You can check the commits to see what I've done in this reproduction project. I reused the tables and relations described in the README of this package (`Comment` → belongs to → `Post` → belongs to → `User` → belongs to → `Country`).

Be sure to initialize the project properly:

```
composer install
php artisan migrate
```

You will see these two errors reported by PHPStan in the tests:

![image](https://github.com/user-attachments/assets/d1b97cc0-ca04-444c-96ac-bdf02277756a)

You can view the errors by running `php ./vendor/bin/phpstan`. 

Let me know if I can help in any way!

**Comment by staudenmeir** [comment] 2024-10-22 20:44
Thanks.

> I recently updated dependencies in this project and I have several errors reported by PHPStan.

Do you have a set of dependency versions (of `belongs-to-through`, `larastan` etc.) where PHPStan runs successfully on your sample project?

**Comment by sebj54** [comment] 2024-10-23 08:28
Here are the versions for the relevant packages (I can provide you the full list of changes but I don't think it's relevant):

### Before update

```
larastan/larastan                           2.9.8              Larastan - Discover bugs in your code without running it. A phpstan/phpstan wrapper for Laravel
laravel/framework                           11.22.0            The Laravel Framework.
phpstan/phpstan                             1.12.3             PHPStan - PHP Static Analysis Tool
```

### After update
```
larastan/larastan                           2.9.9              Larastan - Discover bugs in your code without running it. A phpstan/phpstan wrapper for Laravel
laravel/framework                           11.29.0            The Laravel Framework.
phpstan/phpstan                             1.12.7             PHPStan - PHP Static Analysis Tool
```

Your package has not been updated since my last `composer update`:

```
staudenmeir/belongs-to-through              2.16.1             Laravel Eloquent BelongsToThrough relationships
```

By the way, I just updated the reproduction repo to latest Laravel but it does not change anything.

**Comment by staudenmeir** [comment] 2024-10-27 09:33
Your repository tests `$post->country->id`, but you mean `$post->country?->id`, right (like in your first screenshot)?

`$post->country?->id` gets analyzed correctly when I downgrade `larastan` to `2.9.8`.

The issue doesn't seem to affect Laravel's native relations (e.g. `BelongsTo`): `$post->user?->id` gets analyzed correctly when I use `larastan` with version `2.9.9`.

@calebdw Do you perhaps have an idea here?

**Comment by staudenmeir** [comment] 2024-10-27 09:47
I also noticed that the error message for `$post->country->id` changed in the latest Larastan version:
- `2.9.8`: "Cannot access property $id on App\Models\Country|null"
- `2.9.9`: "Cannot access property $id on mixed."

Maybe that helps with identifying the issue.

**Comment by staudenmeir** [comment] 2024-10-27 11:38
I'm also having similar issues with Larastan `2.9.9` in one of my other repositories:
https://github.com/staudenmeir/laravel-adjacency-list/actions/runs/11539893630/job/32120085541

**Comment by calebdw** [comment] 2024-10-27 12:18
BelongsToThrough should take 3 inner types--- it's likely not defining the `TReturn` which is what Larastan now uses to know the property type

**Comment by calebdw** [comment] 2024-10-27 12:39
Hmm I'm have to take a deeper look after church,  from a quick glance it looks like the phpdoc is missing an asterisk but not sure if that would be the cause

**Comment by sebj54** [comment] 2024-10-28 09:03
> Your repository tests `$post->country->id`, but you mean `$post->country?->id`, right (like in your first screenshot)?

You're right! I should have used that but unfortunately, I rely a lot on PHPStan to warn me about nullable properties so that's the whole point of this issue 😅

I think you're close with your hypothesis, but I don't know what "path" PHPStan follows to resolve related model. Maybe you should compare the return types of each method of `BelongsTo` and `BelongsToThrough`?

Here is a difference I spotted, for instance:

*BelongsTo*

```php
    /**
     * Make a new related instance for the given model.
     *
     * @param  TDeclaringModel  $parent
     * @return TRelatedModel
     */
    protected function newRelatedInstanceFor(Model $parent)
    {
        return $this->related->newInstance();
    }
```

*BelongsToThrough*

```php
    /**
     * Make a new related instance for the given model.
     *
     * @param \Illuminate\Database\Eloquent\Model $parent
     * @return \Illuminate\Database\Eloquent\Model
     */
    protected function newRelatedInstanceFor(Model $parent)
    {
        return $this->related->newInstance();
    }
```

**Comment by sebj54** [comment] 2024-10-30 15:05
Do you want me to file an issue there? 

I don't know if there are other custom relation packages made by someone else but it could be interesting to see if they are facing the same problem.

**Comment by staudenmeir** [comment] 2024-11-05 21:02
> Do you want me to file an issue there?

If you have time, that would be awesome.

> I don't know if there are other custom relation packages made by someone else but it could be interesting to see if they are facing the same problem.

I know these two packages, but they don't seem to be typed "as much" my packages are:
https://github.com/korridor/laravel-has-many-merged
https://github.com/topclaudy/compoships

**Comment by sebj54** [comment] 2024-11-06 19:35
I opened the issue and a Larastan maintainer pointed out that it works with the `main` branch of this package. I just updated with Composer and can confirm!

More info: https://github.com/larastan/larastan/issues/2100#issuecomment-2460553557

Can you release a new version of this package anytime soon? 😁

**Comment by staudenmeir** [comment] 2024-11-06 20:07
Thanks for creating a ticket. I released a new version, but there's definitely an issue with Larastan `2.9.9` that broke the type checks for my other relation packages.

I'll look into that myself.

**Closed by staudenmeir** 2024-11-06 20:07 UTC

**Comment by calebdw** [comment] 2024-11-06 21:07
> but there's definitely an issue with Larastan 2.9.9 that broke the type checks for my other relation packages.

@staudenmeir, Larastan 2.9.9 switched from determining the relation property based on the relation name (e.g., if a relation contained `*Many*` in the name then it would use a collection of objects) to instead grabbing the value of the `TResult` template from the base Relation type. The other relation packages will likely need to be updated to properly extend the Relation class with the right generics.

**Comment by staudenmeir** [comment] 2024-11-09 09:54
Thanks @calebdw.

This package's `BelongsToThrough` relation is the only class that directly extends `Relation`. The other relations extend native Laravel relations like `HasMany` ([example](https://github.com/staudenmeir/laravel-adjacency-list/blob/d875a4d91f96fff5f0f95674d62d144aa14c1744/src/Eloquent/Relations/Ancestors.php)) and (should) inherit their `TResult` value.

Do you know what I would need to change in these cases? Thanks.

**Comment by calebdw** [comment] 2024-11-11 14:46
@staudenmeir, it looks like Larastan is overriding the `TRelatedModel` template to just a `Model`:


```php
function test(Node $node): void
{
    assertType(
        'Staudenmeir\LaravelAdjacencyList\Eloquent\Relations\Graph\Ancestors<Staudenmeir\LaravelAdjacencyList\Types\Graph\Models\Node, Staudenmeir\LaravelAdjacencyList\Types\Graph\Models\Node>',
        $node->ancestors(),
    );
```

is failing with:

```
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------ 
  Line   Graph/Scopes.php                                                                                                                                      
 ------ ------------------------------------------------------------------------------------------------------------------------------------------------------ 
  11     Expected type Staudenmeir\LaravelAdjacencyList\Eloquent\Relations\Graph\Ancestors<Staudenmeir\LaravelAdjacencyList\Types\Graph\Models\Node,           
         Staudenmeir\LaravelAdjacencyList\Types\Graph\Models\Node>, actual:                                                                                    
         Staudenmeir\LaravelAdjacencyList\Eloquent\Relations\Graph\Ancestors<Illuminate\Database\Eloquent\Model,                                               
         Staudenmeir\LaravelAdjacencyList\Types\Graph\Models\Node>                                                                                             

```

**Comment by staudenmeir** [comment] 2024-11-16 10:52
@calebdw Is that a Larastan bug? Should I create an issue?

**Comment by calebdw** [comment] 2024-11-17 05:51
Larastan 3.x  was also just released which removed a bunch of code dealing with the relation types, instead it now relies on the method docs. You might try testing to see if it's fixed in 3.x, and if not then opening an issue

**Comment by staudenmeir** [comment] 2024-11-28 20:38
Thanks @calebdw, it looks like all the issues got solved.
